### ISSUE TITLE
Problems when parsing tabs

### ISSUE THREAD

**Issue by chriscombs** [nodes-ios/ModelBoiler#2]

**Comment by nickskull** [comment]
I think it's actually issues with tabs, not whitespaces. :)

**Comment by mariusc** [comment]
Shouldn't this be an issue for the model-generator and not for ModelBoiler?

Also, I tried this locally and it worked for me in ModelBoiler v.2.2.0 (16).
I updated the tests in model-generator to test for tabs parsing and they passed (https://github.com/nodes-ios/model-generator/pull/8)

@chriscombs @nickskull Can you still reproduce this issue? Or should we close it?

**Comment by dominik-hadl** [comment]
@mariusc Yes, you are right. It should be an issue in model-generator, thanks for the tests, closing this issue for now. 

If it reappears then we can reopen.
