### ISSUE TITLE
Sometimes crashes

### ISSUE THREAD

**Issue by kasperwelner** [nodes-ios/ModelBoiler#9]
KeyCommandManager.swift line 39
change 

guard let appServices = bundle.infoDictionary?["NSServices"]?.firstItem as? [String: AnyObject]

to

guard let appServices = bundle.infoDictionary?["NSServices"]?.firstObject as? [String: AnyObject],

**Comment by mariusc** [comment]
Made it build successfully https://travis-ci.org/nodes-ios/ModelBoiler/builds/122790562
